### PR TITLE
Hunllef Attack Overlay Tracker

### PR DESCRIPTION
**Pull request by sethks**
A very small QOL change that when fighting hunllef, the player will be able to see how many attacks they have performed, how many attacks hunllef has attacked, and the current prayer they should be using.

### CODE REVIEW

**Comment by sethks** [comment]
Example:

**Comment by rdutta** [comment]
Third party client guidelines states features that indicate which prayer to use in any combat situation are unacceptable. Is there an exception to this rule?

As for the attack counters, what is the purpose? Could it be condensed to just show a ratio of attacks delt/received, or is there a need to know the individual numbers?

**Comment by sethks** [comment]
I have removed the prayer tracking as I assumed it was not allowed. Thank you for the confirmation. 

**Player Counter:**
- The "Player Attacks" counter helps the player know when/what weapon they need to switch to as every 6 attacks done to the boss, the boss will change its prayer to what the player is attacking it with.

**Boss Counter:**
- The "Boss Attacks" counter helps to know what prayer to switch to as every 4 attacks done to the player, the boss will switch its attack style. 

I believe this would help beginners get better at The Gauntlet as some of the mental counting/tracking pressure can be relieved by having the information 'drawn' on screen for them.

**Comment by rdutta** [comment]
https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1

firefox_P87RLNLLdu


Confirm before making the PR lol.

**Pull request closed without merging**
